"""empty message

Revision ID: 524e6fd2351e
Revises: 
Create Date: 2022-04-12 13:57:22.326740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '524e6fd2351e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refferalaccount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('state', sa.String(length=2), autoincrement=False, nullable=False),
    sa.Column('zip_code', sa.String(length=5), autoincrement=False, nullable=False),
    sa.Column('industry', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('refferal_account_contacts')
    op.drop_table('refferal_accounts')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey'),
    sa.UniqueConstraint('email', name='contacts_email_key')
    )
    op.create_table('refferal_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('refferal_account_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_refferal_accounts_employees'),
    sa.PrimaryKeyConstraint('id', name='refferal_accounts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('refferal_account_contacts',
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refferal_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['employees.id'], name='refferal_account_contacts_employee_id_fk'),
    sa.ForeignKeyConstraint(['refferal_account_id'], ['refferal_accounts.id'], name='refferal_account_contacts_recceral_account_id_fk'),
    sa.PrimaryKeyConstraint('contact_id', 'refferal_account_id', name='refferal_account_contacts_pk')
    )
    op.drop_table('refferalaccount')
    op.drop_table('contact')
    # ### end Alembic commands ###
